export const ownerConfig = {
  initials: "RR",
  firstName: "Rajesh",
  lastName: "Ranjan",
  experience: { years: 7, months: 10 },
  designation: "Full Stack Developer",
  company: "Business Today Technology",
  organization: "India Today Group",
  description:
    "Experienced Full Stack Developer with expertise in React, Next.js, Node.js, TypeScript, and cloud-based application development.",
  location: { city: "Noida", state: "Uttar Pradesh", country: "India" },
  phone: "+91-9999340771",
  degree: "Bachelor of Technology",
  stream: "Computer Science & Engineering",
  images: {
    profileImage: "/assets/personal-img/profile_photo_3d_cartoon.png",
    greetingsImage: "/assets/personal-img/profile_photo_3d_cartoon.png",
    aboutImage: "/assets/personal-img/profile_photo_3d_cartoon.png",
  },
  typewriterTexts: [
    "Full Stack Developer",
    "Software Developer",
    "Software Engineer",
  ],
  social: {
    github: "rajesh-ranjan-git",
    google: "rajeshranjan8271@gmail.com",
    stackOverflow: "",
    linkedin: "rajesh-ranjan-full-stack-developer",
    twitter: "_rajesh____",
    youtube: "",
    facebook: "rajeshranjan8271",
    instagram: "_rajesh____",
  },
  socialBadge: "github",
  resumeLink:
    "https://drive.google.com/file/d/1L73b_IyVJpdDCkDk1t9dBPB6kEnEHGrW/view?usp=drive_link",
  education: {
    college: {
      name: "JP Institute of Engineering & Technology",
      location: { city: "Meerut", state: "Uttar Pradesh", country: "India" },
      stream: "Computer Science & Engineering",
      gradingSystem: "percent",
      score: 72.8,
      startYear: 2014,
      endYear: 2018,
    },
    highSchool: {
      name: "Indian School of Learning",
      location: { city: "Dhanbad", state: "Jharkhand", country: "India" },
      stream: "Science",
      gradingSystem: "percent",
      score: 78,
      startYear: 2013,
      endYear: 2014,
    },
  },
};
