import {
  FaFacebook,
  FaGithub,
  FaGoogle,
  FaInstagram,
  FaLinkedinIn,
  FaStackOverflow,
  FaXTwitter,
  FaYoutube,
} from "react-icons/fa6";
import { SocialMediaType } from "@/types/types/common.types";

export const socialMedia: SocialMediaType[] = [
  {
    id: "github",
    label: "GitHub",
    url: "https://github.com/rajesh-ranjan-git/",
    color: "text-social-text",
    bgColor: "bg-github",
    hoverColor: "bg-social-hover",
    icon: FaGithub,
  },
  {
    id: "google",
    label: "Google",
    url: "mailto:rajeshranjan8271@gmail.com",
    color: "text-social-text",
    bgColor: "bg-google",
    hoverColor: "bg-social-hover",
    icon: FaGoogle,
  },
  {
    id: "stack-overflow",
    label: "Stack Overflow",
    url: "https://stackoverflow.com/users/7486676/rajesh-ranjan/",
    color: "text-social-text",
    bgColor: "bg-stack-overflow",
    hoverColor: "bg-social-hover",
    icon: FaStackOverflow,
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    url: "https://www.linkedin.com/in/rajesh-ranjan-full-stack-developer/",
    color: "text-social-text",
    bgColor: "bg-linkedin",
    hoverColor: "bg-social-hover",
    icon: FaLinkedinIn,
  },
  {
    id: "twitter",
    label: "Twitter",
    url: "https://x.com/_rajesh____/",
    color: "text-social-text",
    bgColor: "bg-twitter",
    hoverColor: "bg-social-hover",
    icon: FaXTwitter,
  },
  {
    id: "youtube",
    label: "Youtube",
    url: "",
    color: "text-social-text",
    bgColor: "bg-youtube",
    hoverColor: "bg-social-hover",
    icon: FaYoutube,
  },
  {
    id: "facebook",
    label: "Facebook",
    url: "https://www.facebook.com/rajeshranjan8271/",
    color: "text-social-text",
    bgColor: "bg-facebook",
    hoverColor: "bg-social-hover",
    icon: FaFacebook,
  },
  {
    id: "instagram",
    label: "Instagram",
    url: "https://www.instagram.com/_rajesh____/",
    color: "text-social-text",
    bgColor: "bg-instagram",
    hoverColor: "bg-social-hover",
    icon: FaInstagram,
  },
];
