import {
  FaFacebook,
  FaGithub,
  FaGoogle,
  FaInstagram,
  FaLinkedinIn,
  FaPhone,
  FaStackOverflow,
  FaXTwitter,
  FaYoutube,
} from "react-icons/fa6";

export const socialMedia = {
  phone: {
    id: "phone",
    label: "Phone",
    urlPrefix: "tel:",
    color: "text-social-text",
    bgColor: "bg-fixed-dark",
    icon: FaPhone,
  },
  github: {
    id: "github",
    label: "GitHub",
    urlPrefix: "https://github.com",
    color: "text-social-text",
    bgColor: "bg-github",
    icon: FaGithub,
  },
  google: {
    id: "google",
    label: "Google",
    urlPrefix: "mailto:",
    color: "text-social-text",
    bgColor: "bg-google",
    icon: FaGoogle,
  },
  stackOverflow: {
    id: "stack-overflow",
    label: "Stack Overflow",
    urlPrefix: "https://stackoverflow.com/users/7486676",
    color: "text-social-text",
    bgColor: "bg-stack-overflow",
    icon: FaStackOverflow,
  },
  linkedin: {
    id: "linkedin",
    label: "LinkedIn",
    urlPrefix: "https://www.linkedin.com/in",
    color: "text-social-text",
    bgColor: "bg-linkedin",
    icon: FaLinkedinIn,
  },
  twitter: {
    id: "twitter",
    label: "Twitter",
    urlPrefix: "https://x.com",
    color: "text-social-text",
    bgColor: "bg-twitter",
    icon: FaXTwitter,
  },
  youtube: {
    id: "youtube",
    label: "Youtube",
    urlPrefix: "https://www.youtube.com/@",
    color: "text-social-text",
    bgColor: "bg-youtube",
    icon: FaYoutube,
  },
  facebook: {
    id: "facebook",
    label: "Facebook",
    userName: "rajeshranjan8271",
    urlPrefix: "https://www.facebook.com",
    color: "text-social-text",
    bgColor: "bg-facebook",
    icon: FaFacebook,
  },
  instagram: {
    id: "instagram",
    label: "Instagram",
    userName: "_rajesh____",
    urlPrefix: "https://www.instagram.com",
    color: "text-social-text",
    bgColor: "bg-instagram",
    icon: FaInstagram,
  },
};

export const socialMediaList = Object.values(socialMedia);
