export const technologiesConfig = [
  {
    id: "html",
    type: "skill",
    label: "HTML5",
    src: "/assets/tech-img/html-5.svg",
  },
  {
    id: "css",
    type: "skill",
    label: "CSS3",
    src: "/assets/tech-img/css-3.svg",
  },
  {
    id: "sass",
    type: "skill",
    label: "Sass",
    src: "/assets/tech-img/sass.svg",
  },
  { id: "less", type: "skill", label: "Less", src: "" },
  {
    id: "javascript",
    type: "skill",
    label: "JavaScript",
    src: "/assets/tech-img/javascript.svg",
  },
  {
    id: "typescript",
    type: "skill",
    label: "TypeScript",
    src: "/assets/tech-img/typescript.svg",
  },
  {
    id: "react-js",
    type: "skill",
    label: "React JS",
    src: "/assets/tech-img/react.svg",
  },
  {
    id: "next-js",
    type: "skill",
    label: "Next JS",
    src: "/assets/tech-img/next-js.svg",
  },
  { id: "vue", type: "skill", label: "Vue.js", src: "" },
  { id: "nuxt", type: "skill", label: "Nuxt.js", src: "" },
  { id: "angular", type: "skill", label: "Angular", src: "" },
  { id: "svelte", type: "skill", label: "Svelte", src: "" },
  { id: "sveltekit", type: "skill", label: "SvelteKit", src: "" },
  { id: "solid-js", type: "skill", label: "SolidJS", src: "" },
  { id: "astro", type: "skill", label: "Astro", src: "" },
  {
    id: "remix",
    type: "skill",
    label: "Remix",
    src: "/assets/tech-img/remix.svg",
  },
  {
    id: "ember",
    type: "skill",
    label: "Ember",
    src: "/assets/tech-img/ember.svg",
  },
  { id: "tailwind-css", type: "skill", label: "Tailwind CSS", src: "" },
  {
    id: "bootstrap",
    type: "skill",
    label: "Bootstrap",
    src: "/assets/tech-img/bootstrap.svg",
  },
  { id: "material-ui", type: "skill", label: "Material UI", src: "" },
  { id: "chakra-ui", type: "skill", label: "Chakra UI", src: "" },
  { id: "shadcn-ui", type: "skill", label: "shadcn/ui", src: "" },
  {
    id: "styled-components",
    type: "skill",
    label: "Styled Components",
    src: "",
  },
  { id: "emotion", type: "skill", label: "Emotion", src: "" },
  { id: "framer-motion", type: "skill", label: "Framer Motion", src: "" },

  { id: "redux", type: "skill", label: "Redux", src: "" },
  { id: "redux-toolkit", type: "skill", label: "Redux Toolkit", src: "" },
  { id: "zustand", type: "skill", label: "Zustand", src: "" },
  { id: "recoil", type: "skill", label: "Recoil", src: "" },
  { id: "mobx", type: "skill", label: "MobX", src: "" },
  {
    id: "tanstack-query",
    type: "skill",
    label: "TanStack Query",
    src: "",
  },
  {
    id: "node-js",
    type: "skill",
    label: "Node.js",
    src: "/assets/tech-img/node-js.svg",
  },
  { id: "express-js", type: "skill", label: "Express.js", src: "" },
  { id: "nestjs", type: "skill", label: "NestJS", src: "" },
  { id: "fastify", type: "skill", label: "Fastify", src: "" },
  {
    id: "django",
    type: "skill",
    label: "Django",
    src: "/assets/tech-img/django.svg",
  },
  { id: "flask", type: "skill", label: "Flask", src: "" },
  {
    id: "spring-boot",
    type: "skill",
    label: "Spring Boot",
    src: "/assets/tech-img/spring.svg",
  },
  { id: "laravel", type: "skill", label: "Laravel", src: "" },
  { id: "dotnet", type: "skill", label: ".NET", src: "" },
  { id: "react-native", type: "skill", label: "React Native", src: "" },
  { id: "expo", type: "skill", label: "Expo", src: "" },
  {
    id: "flutter",
    type: "skill",
    label: "Flutter",
    src: "/assets/tech-img/flutter.svg",
  },
  { id: "swift", type: "skill", label: "Swift", src: "" },
  {
    id: "kotlin",
    type: "skill",
    label: "Kotlin",
    src: "/assets/tech-img/kotlin.svg",
  },
  { id: "ios", type: "skill", label: "iOS", src: "/assets/tech-img/ios.svg" },
  {
    id: "android",
    type: "skill",
    label: "Android",
    src: "/assets/tech-img/android.svg",
  },

  {
    id: "java",
    type: "skill",
    label: "Java",
    src: "/assets/tech-img/java.svg",
  },
  {
    id: "python",
    type: "skill",
    label: "Python",
    src: "/assets/tech-img/python.svg",
  },
  { id: "c", type: "skill", label: "C", src: "/assets/tech-img/c.svg" },
  {
    id: "cpp",
    type: "skill",
    label: "C++",
    src: "/assets/tech-img/c++.svg",
  },
  {
    id: "csharp",
    type: "skill",
    label: "C#",
    src: "/assets/tech-img/c-sharp.svg",
  },
  { id: "go", type: "skill", label: "Go", src: "" },
  { id: "rust", type: "skill", label: "Rust", src: "" },
  { id: "php", type: "skill", label: "PHP", src: "/assets/tech-img/php.svg" },
  { id: "ruby", type: "skill", label: "Ruby", src: "" },
  {
    id: "dart",
    type: "skill",
    label: "Dart",
    src: "/assets/tech-img/dart.svg",
  },
  {
    id: "my-sql",
    type: "skill",
    label: "MySQL",
    src: "/assets/tech-img/my-sql.svg",
  },
  {
    id: "postgresql",
    type: "skill",
    label: "PostgreSQL",
    src: "/assets/tech-img/postgresql.svg",
  },
  {
    id: "mongo-db",
    type: "skill",
    label: "MongoDB",
    src: "/assets/tech-img/mongo-db.svg",
  },
  { id: "sqlite", type: "skill", label: "SQLite", src: "" },
  {
    id: "redis",
    type: "skill",
    label: "Redis",
    src: "/assets/tech-img/redis.svg",
  },
  {
    id: "firebase",
    type: "skill",
    label: "Firebase",
    src: "/assets/tech-img/firebase.svg",
  },
  { id: "supabase", type: "skill", label: "Supabase", src: "" },
  { id: "appwrite", type: "skill", label: "Appwrite", src: "" },
  { id: "prisma", type: "skill", label: "Prisma", src: "" },
  { id: "typeorm", type: "skill", label: "TypeORM", src: "" },
  { id: "mongoose", type: "skill", label: "Mongoose", src: "" },
  { id: "sequelize", type: "skill", label: "Sequelize", src: "" },
  { id: "hibernate", type: "skill", label: "Hibernate", src: "" },
  { id: "rest-api", type: "skill", label: "REST API", src: "" },
  { id: "graphql", type: "skill", label: "GraphQL", src: "" },
  { id: "grpc", type: "skill", label: "gRPC", src: "" },
  { id: "websocket", type: "skill", label: "WebSocket", src: "" },
  { id: "jwt", type: "skill", label: "JWT", src: "" },
  { id: "oauth", type: "skill", label: "OAuth", src: "" },
  { id: "clerk", type: "skill", label: "Clerk", src: "" },
  { id: "auth-js", type: "skill", label: "Auth.js", src: "" },
  {
    id: "amazon-web-services",
    type: "tool",
    label: "Amazon Web Services",
    src: "/assets/tech-img/amazon-web-services.svg",
  },
  { id: "azure", type: "tool", label: "Microsoft Azure", src: "" },
  {
    id: "google-cloud",
    type: "tool",
    label: "Google Cloud",
    src: "/assets/tech-img/google-cloud.svg",
  },
  { id: "cloudflare", type: "tool", label: "Cloudflare", src: "" },
  { id: "vercel", type: "tool", label: "Vercel", src: "" },
  { id: "netlify", type: "tool", label: "Netlify", src: "" },
  { id: "render", type: "tool", label: "Render", src: "" },
  { id: "railway", type: "tool", label: "Railway", src: "" },
  {
    id: "docker",
    type: "tool",
    label: "Docker",
    src: "/assets/tech-img/docker.svg",
  },
  {
    id: "kubernetes",
    type: "tool",
    label: "Kubernetes",
    src: "/assets/tech-img/kubernets.svg",
  },
  { id: "jenkins", type: "tool", label: "Jenkins", src: "" },
  { id: "github-actions", type: "tool", label: "GitHub Actions", src: "" },
  { id: "terraform", type: "tool", label: "Terraform", src: "" },
  { id: "nginx", type: "tool", label: "NGINX", src: "" },
  {
    id: "packer",
    type: "tool",
    label: "Packer",
    src: "/assets/tech-img/packer.svg",
  },
  {
    id: "vagrant",
    type: "tool",
    label: "Vagrant",
    src: "/assets/tech-img/vagrant.svg",
  },
  { id: "openai", type: "tool", label: "OpenAI API", src: "" },
  { id: "anthropic", type: "tool", label: "Claude API", src: "" },
  { id: "gemini", type: "tool", label: "Gemini API", src: "" },
  { id: "langchain", type: "skill", label: "LangChain", src: "" },
  { id: "hugging-face", type: "tool", label: "Hugging Face", src: "" },
  { id: "ollama", type: "tool", label: "Ollama", src: "" },
  { id: "jest", type: "tool", label: "Jest", src: "" },
  { id: "vitest", type: "tool", label: "Vitest", src: "" },
  { id: "playwright", type: "tool", label: "Playwright", src: "" },
  { id: "cypress", type: "tool", label: "Cypress", src: "" },
  {
    id: "postman",
    type: "tool",
    label: "Postman",
    src: "/assets/tech-img/postman.svg",
  },
  { id: "insomnia", type: "tool", label: "Insomnia", src: "" },

  { id: "git", type: "tool", label: "Git", src: "/assets/tech-img/git.svg" },
  {
    id: "github",
    type: "tool",
    label: "GitHub",
    src: "/assets/tech-img/github.svg",
  },
  {
    id: "gitlab",
    type: "tool",
    label: "GitLab",
    src: "/assets/tech-img/gitlab.svg",
  },
  { id: "bitbucket", type: "tool", label: "Bitbucket", src: "" },
  {
    id: "vs-code",
    type: "tool",
    label: "VS Code",
    src: "/assets/tech-img/visual-studio-code.svg",
  },
  { id: "webstorm", type: "tool", label: "WebStorm", src: "" },
  {
    id: "intellij",
    type: "tool",
    label: "IntelliJ IDEA",
    src: "/assets/tech-img/intellij.svg",
  },
  {
    id: "android-studio",
    type: "tool",
    label: "Android Studio",
    src: "/assets/tech-img/android-studio.svg",
  },
  { id: "xcode", type: "tool", label: "Xcode", src: "" },
  { id: "atom", type: "tool", label: "Atom", src: "/assets/tech-img/atom.svg" },
  {
    id: "pycharm",
    type: "tool",
    label: "PyCharm",
    src: "/assets/tech-img/pycharm.svg",
  },
  {
    id: "visual-studio",
    type: "tool",
    label: "Visual Studio",
    src: "/assets/tech-img/visual-studio.svg",
  },
  { id: "figma", type: "tool", label: "Figma", src: "" },
  {
    id: "adobe-xd",
    type: "tool",
    label: "Adobe XD",
    src: "/assets/tech-img/adobe-xd.svg",
  },
  {
    id: "photoshop",
    type: "tool",
    label: "Photoshop",
    src: "/assets/tech-img/adobe-photoshop.svg",
  },
  { id: "illustrator", type: "tool", label: "Illustrator", src: "" },
  {
    id: "adobe",
    type: "tool",
    label: "Adobe",
    src: "/assets/tech-img/adobe.svg",
  },
  { id: "vite", type: "tool", label: "Vite", src: "" },
  { id: "webpack", type: "tool", label: "Webpack", src: "" },
  { id: "parcel", type: "tool", label: "Parcel", src: "" },
  { id: "turbopack", type: "tool", label: "Turbopack", src: "" },
  { id: "npm", type: "tool", label: "npm", src: "/assets/tech-img/npm.svg" },
  { id: "yarn", type: "tool", label: "Yarn", src: "" },
  { id: "pnpm", type: "tool", label: "pnpm", src: "" },
  { id: "bun", type: "tool", label: "Bun", src: "" },
  { id: "jira", type: "tool", label: "Jira", src: "" },
  { id: "confluence", type: "tool", label: "Confluence", src: "" },
  {
    id: "slack",
    type: "tool",
    label: "Slack",
    src: "/assets/tech-img/slack.svg",
  },
  { id: "notion", type: "tool", label: "Notion", src: "" },
  {
    id: "trello",
    type: "tool",
    label: "Trello",
    src: "/assets/tech-img/trello.svg",
  },
  { id: "clickup", type: "tool", label: "ClickUp", src: "" },
  { id: "sentry", type: "tool", label: "Sentry", src: "" },
  { id: "grafana", type: "tool", label: "Grafana", src: "" },
  { id: "prometheus", type: "tool", label: "Prometheus", src: "" },
  { id: "new-relic", type: "tool", label: "New Relic", src: "" },
  { id: "linux", type: "skill", label: "Linux", src: "" },
  {
    id: "bash",
    type: "skill",
    label: "Bash",
    src: "/assets/tech-img/bash.svg",
  },
  { id: "powershell", type: "skill", label: "PowerShell", src: "" },
  { id: "regex", type: "skill", label: "Regex", src: "" },
  { id: "swagger", type: "tool", label: "Swagger", src: "" },
  { id: "eslint", type: "tool", label: "ESLint", src: "" },
  { id: "prettier", type: "tool", label: "Prettier", src: "" },
  {
    id: "ubuntu",
    type: "skill",
    label: "Ubuntu",
    src: "/assets/tech-img/ubuntu.svg",
  },
  {
    id: "unity",
    type: "tool",
    label: "Unity",
    src: "/assets/tech-img/unity.svg",
  },
];
